### ISSUE TITLE
JWT_CSRF_IN_COOKIES not honored in when @jwt_required used

### ISSUE THREAD

**Issue by jdsjr** [vimalloc/flask-jwt-extended#200]
I have JWT_TOKEN_LOCATION set to 'cookies' and JWT_CSRF_IN_COOKIES set to True. I can see both being sent to my server (in the cookies) on a post to a @jwt_required method.  However, I end up getting a "flask_jwt_extended.exceptions.CSRFError: Missing CSRF token in headers" exception.  It appears that the decorator is still looking for the CSRF token in the header instead of in the cookie.  That doesn't seem right to me.  Can you take a look?  

Stack Trace:

Traceback (most recent call last):
File "/var/task/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/var/task/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/var/task/flask_restplus/api.py", line 325, in wrapper
resp = resource(*args, **kwargs)
File "/var/task/flask/views.py", line 88, in view
return self.dispatch_request(*args, **kwargs)
File "/var/task/flask_restplus/resource.py", line 44, in dispatch_request
resp = meth(*args, **kwargs)
File "/var/task/flask_jwt_extended/view_decorators.py", line 102, in wrapper
verify_jwt_in_request()
File "/var/task/flask_jwt_extended/view_decorators.py", line 31, in verify_jwt_in_request
jwt_data = _decode_jwt_from_request(request_type='access')
File "/var/task/flask_jwt_extended/view_decorators.py", line 265, in _decode_jwt_from_request
decoded_token = decode_function()
File "/var/task/flask_jwt_extended/view_decorators.py", line 251, in <lambda>
decode_functions.append(lambda: _decode_jwt_from_cookies(request_type))
File "/var/task/flask_jwt_extended/view_decorators.py", line 212, in _decode_jwt_from_cookies
raise CSRFError("Missing CSRF token in headers")
flask_jwt_extended.exceptions.CSRFError: Missing CSRF token in headers

**Comment by vimalloc** [comment]
That is correct, otherwise there is no CSRF protection happening. Check this out for some more specific details: https://github.com/vimalloc/flask-jwt-extended/issues/157
