### ISSUE TITLE
"Expected a string value" while implementing redis_blacklist.py

### ISSUE THREAD

**Issue by sham-hq** [vimalloc/flask-jwt-extended#217]
Hi, I am trying to implement redis_blacklist.py and added all the code there. But getting below error. I am not able to figure out what is going wrong here. My application environment is:
Flask: 1.0.2
Flask-JWT-Extended: 3.14.0
Python: 3.6

```
Traceback (most recent call last):
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python_scripts\qr_code_generate_app\qr_generate_controller.py", line 86, in authLogin
    access_token = create_access_token(identity=username)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask_jwt_extended\utils.py", line 134, in create_access_token
    return jwt_manager._create_access_token(identity, fresh, expires_delta)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask_jwt_extended\jwt_manager.py", line 459, in _create_access_token
    json_encoder=config.json_encoder
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask_jwt_extended\tokens.py", line 77, in encode_access_token
    json_encoder=json_encoder)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\flask_jwt_extended\tokens.py", line 31, in _encode_jwt
    json_encoder=json_encoder).decode('utf-8')
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\jwt\api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\jwt\api_jws.py", line 113, in encode
    key = alg_obj.prepare_key(key)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\jwt\algorithms.py", line 140, in prepare_key
    key = force_bytes(key)
  File "D:\python_scripts\scrap_cric\venv\lib\site-packages\jwt\utils.py", line 30, in force_bytes
    raise TypeError('Expected a string value')
TypeError: Expected a string value
```

Please help. Thanks

**Comment by vimalloc** [comment]
Looking at the stack trace I think whatever the encode key is being set to isn’t correct. Are you seeing this with the redis example without any changes? If not can you paste a minimal code example that demonstrates the issue you are having?

**Comment by sham-hq** [comment]
Hi vimalloc,
I was using `app.config["SECRET_KEY"] = uuid.uuid4()`
I replaced uuid.uuid4() with alphanumeric text, now its working. I think error is because of "-" in uuid.uuid4().
Thanks

**Comment by vimalloc** [comment]
Glad you got it worked out. FWIW if you did something like `string(uuid.uuid4())` I would expect it to work as well. But you probably don’t want to generate a new secret every time you start the app. That would cause every user to be logged out when you restarted your application, and would also causeproblems if you ran your application in multiple processes or servers.

**Comment by carscan** [comment]
@vimalloc  I am still getting the above error. 
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
web_1_c77ca4bbd2cd |     rv = self.dispatch_request()
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
web_1_c77ca4bbd2cd |     return self.view_functions[rule.endpoint](**req.view_args)
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
web_1_c77ca4bbd2cd |     resp = resource(*args, **kwargs)
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 89, in view
web_1_c77ca4bbd2cd |     return self.dispatch_request(*args, **kwargs)
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
web_1_c77ca4bbd2cd |     resp = meth(*args, **kwargs)
web_1_c77ca4bbd2cd |   File "/usr/app/static/app/main/controller/dashauth_controller.py", line 38, in post
web_1_c77ca4bbd2cd |     access_jti = get_jti(encoded_token=access_token)
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/flask_jwt_extended/utils.py", line 76, in get_jti
web_1_c77ca4bbd2cd |     return decode_token(encoded_token).get('jti')
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/flask_jwt_extended/utils.py", line 118, in decode_token
web_1_c77ca4bbd2cd |     allow_expired=allow_expired
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/flask_jwt_extended/tokens.py", line 140, in decode_jwt
web_1_c77ca4bbd2cd |     leeway=leeway, options=options, issuer=issuer)
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 92, in decode
web_1_c77ca4bbd2cd |     jwt, key=key, algorithms=algorithms, options=options, **kwargs
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 156, in decode
web_1_c77ca4bbd2cd |     key, algorithms)
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 220, in _verify_signature
web_1_c77ca4bbd2cd |     key = alg_obj.prepare_key(key)
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/jwt/algorithms.py", line 140, in prepare_key
web_1_c77ca4bbd2cd |     key = force_bytes(key)
web_1_c77ca4bbd2cd |   File "/usr/local/lib/python3.6/site-packages/jwt/utils.py", line 30, in force_bytes
web_1_c77ca4bbd2cd |     raise TypeError('Expected a string value')
web_1_c77ca4bbd2cd | TypeError: Expected a string value




 I am passing string key 
JWT_SECRET_KEY = "sasdsdddsdsddsdsds"

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])
    db.init_app(app)
    flask_bcrypt.init_app(app)
    jwt.init_app(app)


@manager.command
def run():
    app.run()

manager.run()
