### ISSUE TITLE
customer flask error handler do not work in user_loader_error_loader

### ISSUE THREAD

**Issue by mozhemeng** [vimalloc/flask-jwt-extended#355]
I have customer flask error and its handler, just like:
error:
```python
class ApiError(Exception):
    code = 0
    msg = ''

    def __init__(self, msg=None, payload=None):
        Exception.__init__(self)
        if msg is not None:
            self.msg = msg
        self.payload = payload

    def to_dict(self):
        return {
            "code": self.code,
            "msg": self.msg,
            "payload": self.payload
        }

class UnauthorizedUserNotExist(ApiError):
    code = 1004
    msg = _("unauthorized user not exist")
```
error handler:
```python
def handle_api_error(error):
    return jsonify(error.to_dict())
```

register error in flask app:
```python
app.register_error_handler(ApiError, handle_api_error)
```

I can use 
```python
raise UnauthorizedUserNotExist
```
in controllers and it worked well

but when i use it in  user_loader_error_loader callback
```python
@jwt.user_loader_error_loader
def custom_user_loader_error(identity):
    raise UnauthorizedUserNotExist
```
it didnt work, and I get 500 error:
```
Traceback (most recent call last):
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2116, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/werkzeug/test.py", line 1121, in run_wsgi_app
    app_iter = iter(app_rv)
TypeError: 'UnauthorizedUserNotExist' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2124, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2116, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/werkzeug/test.py", line 1121, in run_wsgi_app
    app_iter = iter(app_rv)
TypeError: 'UnauthorizedUserNotExist' object is not iterable
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a type.
 * Detected change in '/Users/zmmo/program/my_project/flask-frame/appname/controllers/v1/auth.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 107-287-225
127.0.0.1 - - [11/Sep/2020 14:59:24] "GET /api/v1/test/test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 36, in verify_jwt_in_request
    _load_user(jwt_data[config.identity_claim_key])
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 168, in _load_user
    raise UserLoadError("user_loader returned None for {}".format(identity))
flask_jwt_extended.exceptions.UserLoadError: user_loader returned None for user1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    return handler(e)
  File "/Users/zmmo/program/my_project/flask-frame/venv/lib/python3.7/site-packages/flask_jwt_extended/jwt_manager.py", line 156, in handler_user_load_error
    return self._user_loader_error_callback(identity)
  File "/Users/zmmo/program/my_project/flask-frame/appname/controllers/v1/auth.py", line 41, in custom_user_loader_error
    raise UnauthorizedUserNotExist
appname.errors.error_instance.UnauthorizedUserNotExist
``` 

Is there something wrong in my code?

**Comment by vimalloc** [comment]
`user_loader_error_loader` is also a flask app error handler callback. It looks like core flask doesn't go through the error handler callbacks for exceptions raised inside another error handler. Today I learned.

Instead of raising a new error in `@jwt.user_loader_error_loader`, how about abstracting away the logic for how those errors should be returned as a flask response, that can then be used by both the `@jwt.user_loader_error_loader` and the `ApiError`?

**Comment by mozhemeng** [comment]
thank you for your reply！

I found a way to use my ApiError in the callback by handle it "manually":
```python
@jwt.unauthorized_loader
def unauthorized_loader_callback(s):
    return handle_api_error(Unauthorized())
```
and it works well.

by the way,  I used a extention called "flask_login"  in my code before, and it also provides a decorator  to register error handler callback,  I can simply use my costomer error in that callback just like:
```python
@login_manager.unauthorized_handler
def unauthorized():
    raise Unauthorized
```
I dont know the detial， maybe it can be a reference.

**Comment by vimalloc** [comment]
Thanks for the heads up. If I run into some free time I'll take a look through their code and see how it's handled there. Thanks! :+1:
