### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by colingoodman** [vimalloc/flask-jwt-extended#438]
I am not sure if this is a problem unique to my current environment or the package itself, however there appears to be something wrong with the underlying dependencies:

```
Traceback (most recent call last):
  File "...\main.py", line 5, in <module>
    from api.auth import auth_blueprint
  File "...\api\auth.py", line 7, in <module>
    from flask_jwt_extended import create_access_token, create_refresh_token, jwt_required, get_jwt_identity, get_jwt
  File "...\venv\lib\site-packages\flask_jwt_extended\__init__.py", line 1, in <module>
    from .jwt_manager import JWTManager
  File "...\venv\lib\site-packages\flask_jwt_extended\jwt_manager.py", line 4, in <module>
    from jwt import DecodeError
ImportError: cannot import name 'DecodeError' from 'jwt' (...\venv\lib\site-packages\jwt\__init__.py)
```

I have reinstalled both jwt-extended as well as jwt with no change.

Perhaps something I am relying upon got deprecated somewhere or I somehow ended up with the wrong version of something. Any pointers would be appreciated.

**Comment by colingoodman** [comment]
Used pip to clean up what I had installed and removed the flask-jwt library since it had conflicting dependencies. Works perfect now.
