### ISSUE TITLE
ImportError: cannot import name 'DecodeError' from 'jwt'  (ubuntu 18/python 3.8)

### ISSUE THREAD

**Issue by foozzi** [vimalloc/flask-jwt-extended#456]
```
Traceback (most recent call last):
  File "/root/dmndmn-dev/venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/root/dmndmn-dev/dmndmn/__init__.py", line 20, in <module>
    from flask_jwt_extended import create_access_token
  File "/root/dmndmn-dev/venv/lib/python3.8/site-packages/flask_jwt_extended/__init__.py", line 1, in <module>
    from .jwt_manager import JWTManager
  File "/root/dmndmn-dev/venv/lib/python3.8/site-packages/flask_jwt_extended/jwt_manager.py", line 4, in <module>
    from jwt import DecodeError
ImportError: cannot import name 'DecodeError' from 'jwt' (/root/dmndmn-dev/venv/lib/python3.8/site-packages/jwt/__init__.py
```

**Comment by vimalloc** [comment]
Sounds like there is a different `jwt` module that it's trying to import from. Make sure you only have `PyJWT` installed in your virtualenv (and that it is up to date), and that you don't have a `jwt.py` file or `jwt/` directory in your local path.

**Comment by foozzi** [comment]
> Sounds like there is a different `jwt` module that it's trying to import from. Make sure you only have `PyJWT` installed in your virtualenv (and that it is up to date), and that you don't have a `jwt.py` file or `jwt/` directory in your local path.

thank you. 
i uninstalled module 'jwt' and reinstalled PyJWT and Flask-JWT-Extended

it's work!
