### ISSUE TITLE
flask-jwt-extended, refresh token

### ISSUE THREAD

**Issue by hamideini74** [vimalloc/flask-jwt-extended#532]
Hi , i am using flask-jwt-extended for jwt authentication . i am using flask-restful in my project .
when my refres-token time expired i get this error:
"POST /auth/api/token/refresh HTTP/1.0" 500
`Traceback (most recent call last):
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 340, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_jwt_extended/utils.py", line 128, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_jwt_extended/jwt_manager.py", line 556, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_jwt_extended/tokens.py", line 95, in _decode_jwt
    decoded_token = jwt.decode(
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/jwt/api_jwt.py", line 168, in decode
    decoded = self.decode_complete(
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/jwt/api_jwt.py", line 136, in decode_complete
    self._validate_claims(
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/jwt/api_jwt.py", line 199, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/jwt/api_jwt.py", line 237, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask/app.py", line 1673, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "/home/freecoders/clm/venv/lib/python3.10/site-packages/flask_jwt_extended/jwt_manager.py", line 132, in handle_expired_error
    return self._expired_token_callback(e.jwt_header, e.jwt_data)
TypeError: InvalidToken() takes 1 positional argument but 2 were given` 
 
 but i want take 401 error-code:
 `@jwt.expired_token_loader
@api_bp.errorhandler(ExpiredSignatureError)
@api_bp.errorhandler(InvalidToken)
def InvalidToken(e):
    response = jsonify(e.args[0])
    response.status_code = 401
    return response`

**Comment by vimalloc** [comment]
> InvalidToken() takes 1 positional argument but 2 were given

This is your problem. The callback for ExpiredTokenLoader takes two arguments, not one. Please refer to the documentation here: https://flask-jwt-extended.readthedocs.io/en/stable/api.html#flask_jwt_extended.JWTManager.expired_token_loader

**Comment by hamideini74** [comment]
It is possible to explain more, I can't understand where this function is initialized and why two arguments are sent to it.

**Comment by vimalloc** [comment]
Sure. This goes into a higher level explanation of how the callback functions work to allow you to to change the default behaviors: https://flask-jwt-extended.readthedocs.io/en/stable/changing_default_behavior.html#changing-default-behaviors

> and why two arguments are sent to it.

The two arguments are sent to it so that you can see the JWT data that was sent in to the request, and customize the result based on that data. For example, if you wanted to have a different response for access vs refresh tokens, you could look at `jwt_payload["type"]` to see what kind of token was passed in. 

> but i want take 401 error-code

If you are just looking for a 401 status code when a token is expired, you shouldn't have to do anything. By default this extension will return a 401 with the message "Token has expired". If that's not what you're seeing, you probably have another extension installed that's causing problems with the default flask errorhandlers. That is a bug with their extension, not this one, but you can look at some workarounds for that here: https://github.com/vimalloc/flask-jwt-extended/issues/86#issuecomment-519347386
