### ISSUE TITLE
cannot import name 'DecodeError' from 'jwt'

### ISSUE THREAD

**Issue by legend1998** [vimalloc/flask-jwt-extended#553]
Traceback (most recent call last):
  File "D:\practical\python-fullstack\api\jwtAuth.py", line 2, in <module>
    from flask_jwt_extended import JWTManager, create_access_token, jwt_required, get_jwt_identity, get_jwt
  File "D:\practical\python-fullstack\api\menv\Lib\site-packages\flask_jwt_extended\__init__.py", line 1, in <module>
    from .jwt_manager import JWTManager as JWTManager
  File "D:\practical\python-fullstack\api\menv\Lib\site-packages\flask_jwt_extended\jwt_manager.py", line 8, in <module>
    from jwt import DecodeError
ImportError: cannot import name 'DecodeError' from 'jwt' (D:\practical\python-fullstack\api\menv\Lib\site-packages\jwt\__init__.py)

**Comment by legend1998** [comment]
Am i missing something???

**Comment by vimalloc** [comment]
Sounds like you have a conflicting `jwt` package or file that is causing issues. Please refer to this issue to see if that resolves your problems: https://github.com/vimalloc/flask-jwt-extended/issues/456#issuecomment-955296249
