### ISSUE TITLE
Cookies, set_access_cookies,  TypeError: Expected bytes

### ISSUE THREAD

**Issue by wayneworkman** [vimalloc/flask-jwt-extended#87]
Python version: 2.7.5
mod_wsgi version: 3.4
Apache version: 2.4.6

Everything works fine when I'm using headers. I'm trying to switch from headers to cookies, I'm following along with the example here:
http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html?highlight=set_access_cookies 

Seems very straightforward. I followed along but I'm getting this error in my Apache error log:
```
[Wed Oct 11 15:44:54.583839 2017] [mpm_prefork:notice] [pid 18195] AH00163: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Wed Oct 11 15:44:54.583884 2017] [core:notice] [pid 18195] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Oct 11 15:45:06.184989 2017] [:error] [pid 18196] [remote 127.0.0.1:172] mod_wsgi (pid=18196): Exception occurred processing WSGI script '/opt/rms-api/wsgi.py'.
[Wed Oct 11 15:45:06.185088 2017] [:error] [pid 18196] [remote 127.0.0.1:172] Traceback (most recent call last):
[Wed Oct 11 15:45:06.185110 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
[Wed Oct 11 15:45:06.185579 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     return self.wsgi_app(environ, start_response)
[Wed Oct 11 15:45:06.185612 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
[Wed Oct 11 15:45:06.185646 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     response = self.handle_exception(e)
[Wed Oct 11 15:45:06.185696 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
[Wed Oct 11 15:45:06.185726 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     reraise(exc_type, exc_value, tb)
[Wed Oct 11 15:45:06.185737 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
[Wed Oct 11 15:45:06.185752 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     response = self.full_dispatch_request()
[Wed Oct 11 15:45:06.185764 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
[Wed Oct 11 15:45:06.185779 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     rv = self.handle_user_exception(e)
[Wed Oct 11 15:45:06.185790 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
[Wed Oct 11 15:45:06.185803 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     reraise(exc_type, exc_value, tb)
[Wed Oct 11 15:45:06.185810 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
[Wed Oct 11 15:45:06.185823 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     rv = self.dispatch_request()
[Wed Oct 11 15:45:06.185832 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
[Wed Oct 11 15:45:06.185857 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 11 15:45:06.185866 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/app/api.py", line 192, in login
[Wed Oct 11 15:45:06.186018 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     set_access_cookies(response, token)
[Wed Oct 11 15:45:06.186033 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/flask_jwt_extended/utils.py", line 180, in set_access_cookies
[Wed Oct 11 15:45:06.186112 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     path=config.access_cookie_path)
[Wed Oct 11 15:45:06.186122 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/werkzeug/wrappers.py", line 1064, in set_cookie
[Wed Oct 11 15:45:06.186432 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     charset=self.charset))
[Wed Oct 11 15:45:06.186449 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/werkzeug/http.py", line 978, in dump_cookie
[Wed Oct 11 15:45:06.186619 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     value = to_bytes(value, charset)
[Wed Oct 11 15:45:06.186630 2017] [:error] [pid 18196] [remote 127.0.0.1:172]   File "/opt/rms-api/flask/lib/python2.7/site-packages/werkzeug/_compat.py", line 112, in to_bytes
[Wed Oct 11 15:45:06.186725 2017] [:error] [pid 18196] [remote 127.0.0.1:172]     raise TypeError('Expected bytes')
[Wed Oct 11 15:45:06.186746 2017] [:error] [pid 18196] [remote 127.0.0.1:172] TypeError: Expected bytes
```

Here's a snippet of my code, the set_access_cookies is what's causing the error:
```
        token = {'Token': create_access_token(identity=username)}
        response = jsonify({'login': True})
        set_access_cookies(response, token)
        return response, 200
```

I've done some searching around and found a couple similar issues online:
[https://stackoverflow.com/questions/39858161/typeerror-expected-bytes-in-flask-app](https://stackoverflow.com/questions/39858161/typeerror-expected-bytes-in-flask-app)
[https://teamtreehouse.com/community/typeerror-expected-bytes-when-trying-to-run-bear-flask-app](https://teamtreehouse.com/community/typeerror-expected-bytes-when-trying-to-run-bear-flask-app)

Any help or insight would be appreciated.

**Comment by vimalloc** [comment]
Token should be the raw encoded access token, not a dictionary. Try changing it like such, and I would expect it to start working:

```python
token = create_access_token(identity=username)
```
Let me know if that doesn't fix it the issue!

**Comment by wayneworkman** [comment]
@vimalloc that did fix the issue, thank you very much!
